version: "3.8"

services:
  node_backend:
    container_name: node_messages
    image: node_messages:0.0.4
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=messages_db
      - PGUSER=admin
      - PGPASSWORD=654123
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=654123
      - POSTGRES_DB=messages_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
